### ISSUE TITLE
Fork ScintillaNET-FindReplaceDialog and possibly others in the README

### ISSUE THREAD

**Issue by cbenard** [VPKSoft/ScintillaNET#14]
In [the README](https://github.com/VPKSoft/ScintillaNET/blob/master/README.md), `ScintillaNET-FindReplaceDialog` is mentioned/linked. That's something that I use, but the [NuGet package I use](https://www.nuget.org/packages/ScintillaNET_FindReplaceDialog/) has a dependency on `jacobslusser.ScintillaNET`.

Could you fork [that repo](https://github.com/Stumpii/ScintillaNET-FindReplaceDialog) and put it in NuGet with a dependency on your package? I could fork it and make it dependent on your package, but I think it would make more sense to have it under one maintainer.

**Comment by VPKSoft** [comment]
Sure - I can fork it and add .NET 5 and NET Core support in the process.

**Comment by cbenard** [comment]
Thank you! Looking forward to it.

**Comment by VPKSoft** [comment]
Done - the [ScintillaNET_FindReplaceDialog](https://www.nuget.org/packages/ScintillaNET_FindReplaceDialog/1.5.0) depends now of this [unofficial.ScintillaNET](https://www.nuget.org/packages/unofficial.ScintillaNET/3.8.7) package and requires either:
* NET Framework 4+
* .NET 5
* NET Core

I'll create a PR for out of courtesy to the previous developer - I have no idea if it will be accepted though.

**TODO** is to verify the Scintilla 5+ package to work and then give this one a proper name i.e. *Scintilla.NET.SearchAndReplace* and change the dependency while keeping the same code base.

You can close this issue if everything seems to be OK 👍

**Comment by cbenard** [comment]
I didn't realize you were the maintainer of the linked `ScintillaNET-FindReplaceDialog` already. That's pretty funny and it was confusing at first how you were able to update it.

I'll test it in a little bit to see if I can run my GUI app in `net5.0-windows` in a bit.

**Comment by cbenard** [comment]
I have some problems with dependencies and WCF with .NET 5 that I can't really resolve at this very moment, but I got it working well enough to say LGTM.
