### ISSUE TITLE
Specified font not working when .Technology = Technology.DirectWrite

### ISSUE THREAD

**Issue by wheregone** [VPKSoft/ScintillaNET#19]
It's OK when .Technology = Default, specified font will be displayed.
When .Technology = Technology.DirectWrite, it seems font is reset to default.
do I need to set something else?

**Comment by VPKSoft** [comment]
Hi,
This seems to be Scintilla issue as the technology is set via direct message to the underlying Scintilla control:
```cs
    public Technology Technology
    {
        get
        {
            return (Technology)DirectMessage(NativeMethods.SCI_GETTECHNOLOGY);
        }
        set
        {
            var technology = (int)value;
            DirectMessage(NativeMethods.SCI_SETTECHNOLOGY, new IntPtr(technology));
        }
    }
```
...
```cs
public const int SCI_SETTECHNOLOGY = 2630;
```

See: https://www.scintilla.org/ScintillaDoc.html#SCI_SETTECHNOLOGY

Ps. Sorry for the late response 🙈

**Comment by VPKSoft** [comment]
Closed due inactivity.
