### ISSUE TITLE
Support for SCI_SETSELECTIONLAYER in order to streamline current line highlighting?

### ISSUE THREAD

**Issue by adamstyl** [VPKSoft/ScintillaNET#24]
@VPKSoft 
Terve!

I would like to ask if it would be possible to add support for the `SCI_SETSELECTIONLAYER` native method. I was trying to make current line highlighting to work and I used this:

```
scintillaEditor.CaretLineVisible = true;
scintillaEditor.CaretLineBackColor = Color.Black;
scintillaEditor.CaretLineBackColorAlpha = 255;
```

The problem was that the line was painted full black **over** the text! After some trial and error I realized that `SCI_SETSELECTIONLAYER` could do the trick. More details in scintilla documentation [here](https://www.scintilla.org/ScintillaDoc.html#SCI_SETCARETLINELAYER). I searched for something similar in Scintilla.cs and NativeMethods.cs but I couldn't find anything so I suppose it's not implemented. For me it was as easy to get the desired result by writing 

```
private const int SCI_SETCARETLINELAYER = 2765;
...
scintillaEditor.DirectMessage(SCI_SETCARETLINELAYER, new IntPtr(1), IntPtr.Zero);
```

But it might be more streamlined if the `SC_LAYER_xyz` constants were an enum and there was a respective property to set.

I might be wrong though as I am **really** new to Scintilla(.net) and I might be missing something.

PS: If I'm right though, I could open a pull request if you lack the time.

**Comment by VPKSoft** [comment]
Hi,
I would appreciate a PR - the free time is sort of managing between work, other hobbies and OSS. It would b be better to use an enum for the SC_LAYER_* 👍

**Comment by adamstyl** [comment]
Indeed time is a precious commodity -the most precious I would dare to say. 😎

Please have a look when your time permits at the pull request I opened and feel free to return it back to me if you have remarks or suggestions!
