### ISSUE TITLE
Case insensitive sql lexer

### ISSUE THREAD

**Issue by Vojlas** [VPKSoft/ScintillaNET#27]
Is there any way to make default SQL lexer case insensitive without the need of create my own lexer?

**Comment by VPKSoft** [comment]
[Scintilla](https://scintilla.org)'s SQL lexer seems to be case-insensitive by default as is SQL, see: https://github.com/VPKSoft/ScintillaLexers/blob/master/VPKSoft.ScintillaLexers/CreateSpecificLexer/CreateLexerSql.cs or the whole library: [ScintillaLexers.NET](https://github.com/VPKSoft/ScintillaLexers).

![image](https://user-images.githubusercontent.com/40712699/203349879-6c027402-ae06-4507-b963-854758628410.png)

**Comment by VPKSoft** [comment]
Closed due inactivity.

**Comment by Vojlas** [comment]
I'm sorry for the inactivity. You are correct, SQL lexer is Case-Insensitive. Thank you for the link.

**Comment by VPKSoft** [comment]
No problem - just cleaning the issue list 🙂
