### ISSUE TITLE
Scintilla.Net 5.3.1.3 don't work when Devexpress libraries added to project

### ISSUE THREAD

**Issue by odysseus1973** [VPKSoft/ScintillaNET#28]
Hi!

Github issue from original branch

https://github.com/jacobslusser/ScintillaNET/issues/526

Step-by-step reproduction 

- Create blank WinForms app (Net 7)
- Install Scintilla.Net 5.3.1.3 nuget package
- Put Scintilla.Net control on form from toolbox
- All works fine
- Add Devexpress libraries to project (via open DevExpress Project Settings and click Add Libraries)
- Try to open Form In Design mode
- Scintilla control disappear.
- Try to put Scintilla control on form again - we get the following error

```
Request failures: DesignerHosts/CreateComponent.
                       Microsoft.DotNet.DesignTools.Client.DesignToolsServerException: Method not found: 'Void System.Security.AccessControl.MutexAccessRule..ctor(System.Security.Principal.IdentityReference, System.Security.AccessControl.MutexRights, System.Security.AccessControl.AccessControlType)'.

                       For information on how to troubleshoot the designer refer to the guide at https://aka.ms/winforms/designer/troubleshooting.
```

- Remove Devexpress package from project - all works fine now

Detailed description of problem from Devexpress

https://supportcenter.devexpress.com/ticket/details/t1133409/scintilla-net-5-3-1-3-don-t-work-when-devexpress-libraries-added-to-project

I understand that you do not use commercial libraries, but please see what you can do

Thanks!

**Comment by VPKSoft** [comment]
Hi,
I can use the DevExpress evaluation to debug the issue - when I have the time.  I'm not sure if the Mutex creation is even required in the constructor of the control. It seems to relate to file use synchronization among processes, [StackOverflow](https://stackoverflow.com/questions/229565/what-is-a-good-pattern-for-using-a-global-mutex-in-c/229567#229567) when extracting the Scintilla native DLL if one doesn't exist already.

**Comment by VPKSoft** [comment]
Hi. the control should now work with the DevExpress library in design mode. The package was already targeting .NET 6
> If you have time, add support for net 6 and net 7, please

.NET 7 TFM was added.
